// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gnanasuriyan/go-message-server/app"
	"github.com/gnanasuriyan/go-message-server/app/repositories"
	"github.com/gnanasuriyan/go-message-server/app/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func GetServer() app.IServer {
	userRepository := &repositories.UserRepository{}
	messageService := &services.MessageService{
		UserRepository: userRepository,
	}
	server := &app.Server{
		MessageService: messageService,
	}
	return server
}

// wire.go:

var repositorySet = wire.NewSet(repositories.NewUserRepository)

var serviceSet = wire.NewSet(services.NewMessageService, services.NewUserService)
