// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gnanasuriyan/go-message-server/app"
)

// Injectors from wire.go:

func GetServer() app.IServer {
	server := &app.Server{}
	return server
}
